# Generated by Django 5.1.1 on 2024-10-03 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngredientCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
            ],
        ),
        migrations.CreateModel(
            name="RecipeBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipeName",
                    models.CharField(max_length=100, verbose_name="recipe name"),
                ),
                ("img", models.URLField(verbose_name="image")),
                ("ingredients", models.TextField(verbose_name="ingredients")),
                ("link", models.URLField(verbose_name="link")),
            ],
        ),
        migrations.CreateModel(
            name="IngredientsToRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.ingredientcategory",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.recipebook",
                    ),
                ),
            ],
        ),
    ]
