# Generated by Django 5.1.1 on 2024-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecipeBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipeName",
                    models.CharField(max_length=100, verbose_name="recipe name"),
                ),
                ("img", models.URLField(verbose_name="image")),
                ("ingredients", models.TextField(verbose_name="ingredients")),
            ],
        ),
    ]
